version: "3.4"

networks:
  default:

services:
  core: &service
    container_name: ldigital-core
    environment:
      - RUN_LEVEL=dev
    entrypoint:
      - uvicorn
      - services.core:app
      - --host=0.0.0.0
      - --reload
    build:
      context: server
      dockerfile: docker/Dockerfile.server
      target: dev
    volumes:
      - ./server:/opt/app
    networks:
      - default
    restart: unless-stopped
    depends_on:
      - postgres
  postgres:
    container_name: ldigital-postgres
    image: mdillon/postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: ldigital
    networks:
      - default
    volumes:
      - ./.docker_data/postgres:/var/lib/postgresql/data
  nginx:
    build:
      context: nginx
    container_name: ldigital-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - core
    networks:
      - default
