"""

Revision ID: 43a8e0f63f19
Revises: 54f206043dfa
Create Date: 2020-06-20 20:03:32.222948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43a8e0f63f19'
down_revision = '54f206043dfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program', 'rating')
    # ### end Alembic commands ###
