"""

Revision ID: 54f206043dfa
Revises: 2b7619c24cb4
Create Date: 2020-06-20 19:43:43.195708

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '54f206043dfa'
down_revision = '2b7619c24cb4'
branch_labels = None
depends_on = None


def upgrade():
    ### commands manually generated by Vasiliy Kovalev - please adjust! ###
    op.alter_column(
        'program',
        'name',
        existing_type=sa.VARCHAR(length=25),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        'discipline',
        'name',
        existing_type=sa.VARCHAR(length=25),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    ### end Alembic commands ###


def downgrade():
    ### commands manually generated by Vasiliy Kovalev - please adjust! ###
    op.alter_column(
        'program',
        'name',
        existing_type=sa.String(length=25),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )

    op.alter_column(
        'discipline',
        'name',
        existing_type=sa.VARCHAR(length=25),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    ### end Alembic commands ###
