"""

Revision ID: 9a0dd7bca5ef
Revises: bd398edb7d68
Create Date: 2020-06-19 22:21:19.814725

"""
import datetime

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9a0dd7bca5ef'
down_revision = 'bd398edb7d68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'program_template',
        sa.Column('program_template_id', sa.Integer(), nullable=False),
        sa.Column('hours', sa.Integer(), nullable=True),
        sa.Column('category', sa.String(length=25), nullable=True),
        sa.PrimaryKeyConstraint('program_template_id'),
        sa.UniqueConstraint('category'),
    )
    op.create_index(
        op.f('ix_program_template_program_template_id'),
        'program_template',
        ['program_template_id'],
        unique=False,
    )
    op.add_column('program', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('program', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program', 'deleted_at')
    op.drop_column('program', 'created_at')
    op.create_table(
        'spatial_ref_sys',
        sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
        sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
        sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
        sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
        sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey'),
    )
    op.drop_index(op.f('ix_program_template_program_template_id'), table_name='program_template')
    op.drop_table('program_template')
    # ### end Alembic commands ###
