"""

Revision ID: bd398edb7d68
Revises: abb9ddccf3d3
Create Date: 2020-06-19 20:19:03.621549

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bd398edb7d68'
down_revision = 'abb9ddccf3d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parameter', 'value', existing_type=sa.VARCHAR(length=100), nullable=True)
    op.create_unique_constraint(None, 'parameter', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parameter', type_='unique')
    op.alter_column('parameter', 'value', existing_type=sa.VARCHAR(length=100), nullable=False)
    # ### end Alembic commands ###
